apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-mlflow
data:
  default.conf: |
    upstream node {
      server localhost:5000;
    }
    server {
        server_name             _;
        listen                  8080;
        location / {
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header Host {{ .Values.ingressHost }};
            proxy_pass http://node;
            proxy_redirect off;
            port_in_redirect off;
            auth_basic "MLflow UI Login";
            auth_basic_user_file /etc/nginx/secrets/passwd;
        }
    }