apiVersion: v1
kind: Secret
metadata:
  name: mlflow-s3-credentials
type: Opaque
stringData:
  S3_ENDPOINT_URL: {{ .Values.s3EndpointUrl }}
  AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey }}