{{- if eq .Values.ingressType "Route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mlflow-ui-route
  {{- if .Values.routeWhitelist }}
  annotations:
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.routeWhitelist }}
  {{- end }}
spec:
  {{- if .Values.ingressHost }}
  host: {{ .Values.ingressHost }}
  {{- end }}
  to:
    kind: Service
    name: mlflow-ui-service
    weight: 100
  port:
    targetPort: mlflow-ui-service
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
status:
  ingress: []
{{- end}}