apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the API pods
  name: mlflow-models-service
  labels:
    app: mlflow-models
spec:
  ports:
    - name: models-service-port
      port: 80
      targetPort: 5001
  selector:
    name: mlflow-models