apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: MLflow Models
  name: mlflow-models
spec:
  replicas: 0
  selector:
    matchLabels:
      name: mlflow-models
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mlflow-models
        app: mlflow
      name: mlflow
    spec:
      containers:
        - name: mlflow-models
          image: {{ .Values.apiImage }}
          imagePullPolicy: Always
          command: ["sh", "./startup/startup.sh"]
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 1600m
              memory: 1Gi
          ports:
            - containerPort: 5001
          volumeMounts:
            - name: {{ .Values.storageName }}-vol
              mountPath: /mnt/{{ .Values.storageName }}-pvc
            - name: mlflow-models-startup-vol
              mountPath: "/startup"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-s3-credentials
                  key: AWS_ACCESS_KEY_ID
                  optional: true
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-s3-credentials
                  key: AWS_SECRET_ACCESS_KEY
                  optional: true
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: mlflow-s3-credentials
                  key: S3_ENDPOINT_URL
                  optional: true
          envFrom:
            - configMapRef:
                name: models-cfg
                optional: true
      volumes:
        - name: mlflow-models-startup-vol
          configMap:
            name: mlflow-models-startup-cfg
            items:
              - key: startup.sh
                path: startup.sh
        - name: {{ .Values.storageName }}-vol
          persistentVolumeClaim:
            claimName: {{ .Values.storageName }}-pvc
