apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-models-startup-cfg
data:
  startup.sh: |
    #!/bin/sh
    if [ "$MODELS_URI" ];
    then
        mlflow models serve --model-uri=$MODELS_URI --port=5001 --host=0.0.0.0 --no-conda
    else
        echo "Model URI not specified to config map. Cannot startup serving."
    fi